const{open,BASE}=require('./.pw.tmp.cjs');
const OUT='/private/tmp/claude-501/-Users-prakrit-firstmate-projects-proplane-claude-3/465f868e-c1f2-459a-807b-be3cd898b80f/scratchpad/shots/';
(async()=>{const{b,p}=await open('vendor');
await p.goto(BASE+'/vendor/profile?tab=business',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);
await p.fill('[data-attr="vendor-business-name"]','Juniper Services');await p.fill('[data-attr="vendor-business-contact-name"]','Jordan Rivera');await p.fill('[data-attr="vendor-business-service-area"]','Seattle · Plumbing');
await p.click('[data-attr="vendor-business-profile-save"]');await p.waitForTimeout(2500);await p.screenshot({path:OUT+'vendor-business.png'});
await p.goto(BASE+'/vendor/profile?tab=work-contacts',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);
await p.fill('[data-attr="vendor-work-phone"]','2065550142');await p.fill('[data-attr="vendor-work-email"]','office@juniper.example');await p.click('[data-attr="vendor-work-contacts-save"]');await p.waitForTimeout(2500);await p.screenshot({path:OUT+'vendor-work-contacts.png'});
await p.goto(BASE+'/vendor/profile?tab=work-contacts',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);
console.log('persisted phone:',await p.inputValue('[data-attr="vendor-work-phone"]'),'email:',await p.inputValue('[data-attr="vendor-work-email"]'));
await p.goto(BASE+'/vendor/profile?tab=workspaces',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);await p.screenshot({path:OUT+'vendor-workspaces.png'});
console.log((await p.locator('main').innerText()).slice(0,400));
await p.goto(BASE+'/vendor/work-orders',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);await p.screenshot({path:OUT+'vendor-services.png'});
await p.goto(BASE+'/vendor/tasks',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);await p.screenshot({path:OUT+'vendor-tasks.png'});
await b.close();})().catch(e=>{console.error(e.message.slice(0,300));process.exit(1)});
