const{open,BASE}=require('./.pw.tmp.cjs');
const OUT='/private/tmp/claude-501/-Users-prakrit-firstmate-projects-proplane-claude-3/465f868e-c1f2-459a-807b-be3cd898b80f/scratchpad/shots/';
(async()=>{const{b,p}=await open('resident');
await p.goto(BASE+'/resident/tour/pending',{waitUntil:'domcontentloaded'});await p.waitForTimeout(3000);
await p.locator('[data-attr="resident-tour-list"]').getByText(/Sep 15/).first().click();await p.waitForTimeout(2500);
console.log('detail',p.url());await p.screenshot({path:OUT+'resident-tour-detail.png'});
console.log('actions R/M/C:',await p.locator('[data-attr="resident-tour-reschedule"]').count(),await p.locator('[data-attr="resident-tour-message-manager"]').count(),await p.locator('[data-attr="resident-tour-cancel"]').count(),'apply:',await p.locator('[data-attr="resident-tour-apply"]').count());
await p.locator('[data-attr="resident-tour-cancel"]').click();await p.waitForTimeout(800);
await p.screenshot({path:OUT+'resident-tour-cancel-confirm.png'});
await p.getByRole('button',{name:'Cancel tour',exact:true}).last().click();await p.waitForTimeout(4000);
console.log('after cancel',p.url());await p.screenshot({path:OUT+'resident-tour-after-cancel.png'});
const t=await p.locator('[data-attr="resident-tour-list"]').innerText().catch(()=>'');console.log('DECLINED LIST',t.slice(0,200));
await b.close();})().catch(e=>{console.error(e.message.slice(0,300));process.exit(1)});
