export const LEASE_AI_REVIEW_DISCLAIMER =
  "This lease was generated by AI. Please review carefully before sending to the tenant. This is not legal advice.";

/** Remove AI review disclaimer text from manager notes / thread bodies. */
export function stripLeaseAiReviewDisclaimer(text: string | null | undefined): string {
  let result = String(text ?? "");
  if (!result.trim()) return "";
  while (result.includes(LEASE_AI_REVIEW_DISCLAIMER)) {
    result = result.split(LEASE_AI_REVIEW_DISCLAIMER).join("");
  }
  result = result.replace(/\s*AI-generated draft\.\s*/gi, " ");
  result = result.replace(/\s{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();
  result = result.replace(/^\.\s*/, "").replace(/\s+\./g, ".").trim();
  return result;
}

/** Remove AI disclaimer banner from saved generated HTML (legacy rows). */
export function stripLeaseAiDisclaimerFromHtml(html: string | null | undefined): string | null {
  if (!html) return null;
  let result = html.replace(/<div class="ai-disclaimer"[^>]*>[\s\S]*?<\/div>\s*/gi, "");
  while (result.includes(LEASE_AI_REVIEW_DISCLAIMER)) {
    result = result.split(LEASE_AI_REVIEW_DISCLAIMER).join("");
  }
  return result;
}

/** True when the lease document was AI-generated HTML (not a manager-uploaded PDF). */
export function leaseUsesAiGeneratedHtml(row: {
  generatedHtml?: string | null;
  managerUploadedPdf?: { dataUrl?: string | null } | null;
}): boolean {
  return Boolean(row.generatedHtml?.trim() && !row.managerUploadedPdf?.dataUrl);
}

export function leaseCss(): string {
  return `
    * { box-sizing: border-box; }
    body { font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif; color: #111; line-height: 1.5; max-width: 820px; margin: 0 auto; padding: 32px 24px 64px; font-size: 11pt; }
    h1 { font-size: 1.4rem; text-align: center; margin: 0 0 0.15rem; font-weight: 700; letter-spacing: .02em; }
    .sub { text-align: center; font-size: 0.82rem; color: #555; margin-bottom: 0.5rem; }
    .generated { text-align: center; font-size: 0.8rem; color: #777; margin-bottom: 1.5rem; }
    h2 { font-size: 1rem; margin: 1.6rem 0 0.45rem; border-bottom: 2px solid #111; padding-bottom: 0.2rem; text-transform: uppercase; letter-spacing: .04em; }
    h3 { font-size: 0.95rem; margin: 1rem 0 0.3rem; text-decoration: underline; }
    p { margin: 0.45rem 0; }
    ol, ul { margin: 0.35rem 0 0.6rem 1.4rem; }
    li { margin: 0.25rem 0; }
    table { width: 100%; border-collapse: collapse; margin: 0.6rem 0 1rem; font-size: 0.93rem; }
    th, td { border: 1px solid #999; padding: 6px 9px; text-align: left; vertical-align: top; }
    th { background: #f0f0f0; font-weight: 700; }
    .total-row th, .total-row td { font-weight: 700; background: #f9f9f9; }
    table.fee-table td.amount, table.fee-table th.amount { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  table.fee-table .total-row td.amount { font-size: 1.02em; }
    p.fee-note { font-size: 0.88rem; color: #444; margin: -0.35rem 0 1rem; }
    ul.lease-shared-spaces { margin: 0.5rem 0 1rem 1.35rem; padding: 0; }
    ul.lease-shared-spaces li { margin: 0.35rem 0; }
    .addendum { border-top: 3px double #333; margin-top: 3rem; padding-top: 1.5rem; }
    .disclosure-review { border: 2px solid #7f1d1d; padding: 10px 12px; margin: 0 0 1.25rem; background: #fff7ed; }
    .disclosure-review p:first-child { margin-top: 0; }
    .disclosure-review p:last-child, .disclosure-review ul:last-child { margin-bottom: 0; }
    .page-break { page-break-before: always; }
    @media print { body { padding: 12px; font-size: 10pt; } }
  `;
}

export type LeaseJurisdictionTemplateConfig = {
  headerSubtitle: string;
  /** Optional branded title above the agreement name (Seattle Axis generic leases). */
  brandTitle?: string;
  /** Default late fee when listing does not specify one. */
  defaultLateFeeUsd?: number;
  governingLawParagraph: string;
  municipalComplianceParagraph?: string;
  shortTermPurposeParagraph: string;
  lateFeeStatuteRef: string;
  depositStatuteRef: string;
  landlordEntryStatuteRef: string;
  residentMaintenanceStatuteRef: string;
  defaultNoticeStatuteRef: string;
  /**
   * Landlord habitability-duty statute. OPTIONAL and deliberately unset for California:
   * the Washington citation used to be hardcoded in the template body, so it printed on
   * every California lease too. Omitted renders the heading with no citation, which is the
   * only safe default. Never populate this without a verified source.
   */
  landlordMaintenanceStatuteRef?: string;
  /** Optional citation for returned-payment rules, rendered only when verified for this jurisdiction. */
  returnedPaymentStatuteRef?: string;
  /** Optional citation for a resident's ongoing liability after an early termination. */
  earlyTerminationStatuteRef?: string;
  /** Optional citation for smoke-alarm requirements. */
  smokeAlarmStatuteRef?: string;
  /** Optional citation for carbon-monoxide-alarm requirements. */
  carbonMonoxideAlarmStatuteRef?: string;
  /**
   * Jurisdiction-specific NUMERIC lease terms.
   *
   * These were hardcoded in the template body with Washington figures, so every California
   * lease printed a WA notice period, a WA deposit-return window, and a WA minimum heat
   * temperature. They are optional for the same reason `landlordMaintenanceStatuteRef` is:
   * a value is set only where it came from a verified source, and an omitted one falls back
   * to language that asserts no specific figure ("as required by applicable law"). Stating a
   * wrong number on an executed lease is worse than stating none. Never populate these for a
   * jurisdiction without confirming the figure for THAT jurisdiction.
   */
  monthToMonthTerminationNotice?: string;
  depositReturnWindow?: string;
  minimumHeatTemperature?: string;
};

/**
 * Statewide Washington. `SEATTLE_LEASE_CONFIG` derives from this, so a statute or term that
 * applies state-wide is written ONCE. Only genuinely city-specific values are overridden.
 */
export const WASHINGTON_LEASE_CONFIG: LeaseJurisdictionTemplateConfig = {
  headerSubtitle: "State of Washington",
  governingLawParagraph:
    "This Agreement is governed by the laws of the <strong>State of Washington</strong> (RCW Title 59) and, where applicable, the ordinances of the city and county in which the Premises are located. If any provision is found invalid, the remainder shall remain in full force. This document, together with any signed addenda, constitutes the entire agreement between the parties. No oral representations are binding. Amendments require written signatures of both parties.",
  shortTermPurposeParagraph:
    "The Guest is staying temporarily as a short-term lodger / guest only. This agreement does not create a landlord-tenant relationship under Washington law. The stay is intended to be exempt from RCW 59.18.040 where legally applicable.",
  lateFeeStatuteRef: "RCW 59.18.283",
  depositStatuteRef: "RCW 59.18.260–.280",
  landlordEntryStatuteRef: "RCW 59.18.150",
  residentMaintenanceStatuteRef: "RCW 59.18.130",
  landlordMaintenanceStatuteRef: "RCW 59.18.060",
  defaultNoticeStatuteRef: "RCW 59.12.030",
  monthToMonthTerminationNotice: "at least 20 days before the end of any monthly rental period",
  depositReturnWindow: "Within 30 days after termination of the tenancy and vacancy of the Premises",
  minimumHeatTemperature: "68°F",
};

export const SEATTLE_LEASE_CONFIG: LeaseJurisdictionTemplateConfig = {
  ...WASHINGTON_LEASE_CONFIG,
  // Seattle-only branding and late-fee default. Deliberately NOT on the statewide config:
  // a Spokane lease must not inherit a Seattle brand line, and no verified statewide figure
  // exists, so the rest of Washington falls back to the builder's own default.
  brandTitle: "PROPLANE SEATTLE HOUSING",
  defaultLateFeeUsd: 75,
  headerSubtitle: "State of Washington · King County",
  municipalComplianceParagraph:
    "This Agreement shall be interpreted consistently with the Washington Residential Landlord-Tenant Act (RCW Chapter 59.18). If the Premises are located within the City of Seattle, applicable Seattle rental regulations (including notice, just-cause, relocation, or habitability rules) shall apply to the minimum extent required by law.",
  governingLawParagraph:
    "This Agreement is governed by the laws of the <strong>State of Washington</strong> (RCW Title 59) and, where applicable, the ordinances of the City of Seattle. If any provision is found invalid, the remainder shall remain in full force. This document, together with any signed addenda, constitutes the entire agreement between the parties. No oral representations are binding. Amendments require written signatures of both parties.",
};

/**
 * Statewide California, for any CA property outside San Francisco.
 *
 * The three numeric terms are deliberately UNSET: the values previously printed here were
 * Washington's, and no verified California figures exist in this repo. They render as
 * "as required by applicable law" until someone sources them.
 */
export const CALIFORNIA_LEASE_CONFIG: LeaseJurisdictionTemplateConfig = {
  headerSubtitle: "State of California",
  governingLawParagraph:
    "This Agreement is governed by the laws of the <strong>State of California</strong> and, where applicable, the ordinances of the city and county in which the Premises are located. If any provision is found invalid, the remainder shall remain in full force. This document, together with any signed addenda, constitutes the entire agreement between the parties. No oral representations are binding. Amendments require written signatures of both parties.",
  shortTermPurposeParagraph:
    "The Guest is staying temporarily as a short-term lodger / guest only. This agreement does not create a landlord-tenant relationship under California law except to the minimum extent required by applicable statute.",
  lateFeeStatuteRef: "California Civil Code",
  depositStatuteRef: "California Civil Code §§ 1950.5 et seq.",
  landlordEntryStatuteRef: "California Civil Code § 1954",
  residentMaintenanceStatuteRef: "California Civil Code",
  defaultNoticeStatuteRef: "California Code of Civil Procedure",
};

export const SAN_FRANCISCO_LEASE_CONFIG: LeaseJurisdictionTemplateConfig = {
  ...CALIFORNIA_LEASE_CONFIG,
  headerSubtitle: "State of California · City and County of San Francisco",
  municipalComplianceParagraph:
    "If the Premises are located within the City and County of San Francisco, the parties agree that the San Francisco Rent Ordinance (SF Administrative Code Chapter 37) and other applicable local rental regulations shall apply to the minimum extent required by law, including notice, habitability, and relocation requirements where applicable.",
  governingLawParagraph:
    "This Agreement is governed by the laws of the <strong>State of California</strong> and, where applicable, the ordinances of the City and County of San Francisco. If any provision is found invalid, the remainder shall remain in full force. This document, together with any signed addenda, constitutes the entire agreement between the parties. No oral representations are binding. Amendments require written signatures of both parties.",
};

/**
 * Code-owned lease configuration registry. Adding a jurisdiction requires one verified
 * state entry here, its disclosure rules in `leases/disclosure-clause-rules.json`, and
 * no new HTML builder. A city may overlay its state's config only where a verified local
 * rule requires a difference.
 */
export type LeaseJurisdictionRegistryEntry = {
  config: LeaseJurisdictionTemplateConfig;
  /** Scope name used by the disclosure rules catalog for state-level rules. */
  ruleScope: string;
  cities?: Readonly<
    Record<
      string,
      {
        config: LeaseJurisdictionTemplateConfig;
        /** Scope name used by the disclosure rules catalog for city-level rules. */
        ruleScope: string;
      }
    >
  >;
};

export const LEASE_JURISDICTION_TEMPLATE_REGISTRY: Readonly<Record<string, LeaseJurisdictionRegistryEntry>> = {
  CA: {
    config: CALIFORNIA_LEASE_CONFIG,
    ruleScope: "california",
    cities: {
      san_francisco: {
        config: SAN_FRANCISCO_LEASE_CONFIG,
        ruleScope: "san_francisco",
      },
    },
  },
  WA: {
    config: WASHINGTON_LEASE_CONFIG,
    ruleScope: "washington",
    cities: {
      seattle: {
        config: SEATTLE_LEASE_CONFIG,
        ruleScope: "seattle",
      },
    },
  },
};
