import type { MoveInFormSummary } from "../../../src/lib/move-in-forms/types";

const base = {
  managerUserId: "mgr-1",
  source: "builder" as const,
  signedDocumentSha256: null,
  remindedAt: null,
  managerViewedAt: null,
  questionCount: 6,
  photoCount: 0,
  signed: false,
};

/** One copy per Blocks mode, so the row's lock/unlock glyph fact is visible for each. */
export const FORMS = [
  {
    ...base,
    id: "copy-1",
    applicationId: "AXIS-1",
    propertyId: "prop-1",
    propertyLabel: "Alder Row",
    roomLabel: "Room 1",
    residentName: "Maya Chen",
    residentEmail: "maya@example.com",
    formId: "tpl-intake",
    formName: "Resident intake",
    kind: "intake",
    blocks: "move_in_details",
    status: "sent",
    sentAt: "2026-09-28T17:00:00.000Z",
    dueAt: "2026-10-12T17:00:00.000Z",
    submittedAt: null,
  },
  {
    ...base,
    id: "copy-2",
    applicationId: "AXIS-2",
    propertyId: "prop-1",
    propertyLabel: "Alder Row",
    roomLabel: "Room 2",
    residentName: "Marcus Lee",
    residentEmail: "marcus@example.com",
    formId: "tpl-movein",
    formName: "Move-in checklist",
    kind: "move-in",
    blocks: "lease_signing",
    status: "sent",
    sentAt: "2026-09-20T17:00:00.000Z",
    dueAt: "2026-10-02T17:00:00.000Z",
    submittedAt: null,
  },
  {
    ...base,
    id: "copy-3",
    applicationId: "AXIS-3",
    propertyId: "prop-2",
    propertyLabel: "Birch Court",
    roomLabel: "Whole house",
    residentName: "Sofia Diaz",
    residentEmail: "sofia@example.com",
    formId: "tpl-screen",
    formName: "Approval questionnaire",
    kind: "other",
    blocks: "approval",
    status: "sent",
    sentAt: "2026-10-01T17:00:00.000Z",
    dueAt: "2026-10-20T17:00:00.000Z",
    submittedAt: null,
  },
  {
    ...base,
    id: "copy-4",
    applicationId: "AXIS-4",
    propertyId: "prop-2",
    propertyLabel: "Birch Court",
    roomLabel: "Room 4",
    residentName: "Liam Foster",
    residentEmail: "liam@example.com",
    formId: "tpl-out",
    formName: "Move-out walkthrough",
    kind: "move-out",
    blocks: "nothing",
    status: "submitted",
    sentAt: "2026-09-01T17:00:00.000Z",
    dueAt: "2026-09-15T17:00:00.000Z",
    submittedAt: "2026-09-14T17:00:00.000Z",
    signed: true,
  },
] as unknown as MoveInFormSummary[];
